# Generated by Django 3.0.2 on 2020-10-13 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0046_auto_20201013_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='improvementplan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Improvement plan:')),
            ],
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='nonconfdetails',
            field=models.TextField(blank=True, null=True, verbose_name='Additional description'),
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='nonconformity',
            field=models.CharField(choices=[('1', 'Support/Resource'), ('2', 'Planning'), ('3', 'IITS(Information, Instructions, Training, Supervision)'), ('4', 'Performance monitoring'), ('5', 'Evaluation'), ('6', 'Risk/Vulnerability Assessment'), ('7', 'Leadership'), ('8', 'Other')], default='Other', max_length=200, verbose_name='Reason: cause of nonconformity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-13102020137', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-13102020137', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-13102020127', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-13102020160', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-13102020294', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-13102020125', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-13102020160', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-13102020128', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='improveplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='improveplan', to='operations_9001.improvementplan', verbose_name='Improvement plan:'),
        ),
    ]
