# Generated by Django 3.0.2 on 2020-10-14 08:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0050_auto_20201014_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='Initiativenes',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Idea Development'), ('2', 'Effective use of resources'), ('3', 'Self drive/motivation')], default=1, max_length=5, verbose_name='Initiativeness & Resourcefulness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Oral and Written'), ('2', 'Clarity of Information shared'), ('3', 'Accuracy of Information shared')], default=1, max_length=5, verbose_name='Communication Skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='planing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Establishing Priorities'), ('2', 'Meeting Deadlines'), ('3', 'Planning of Tasks')], default=1, max_length=5, verbose_name='Planning & Organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='problemsolving',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Response promptness'), ('2', 'Level of Judgement'), ('3', 'Solution Quality')], default=1, max_length=5, verbose_name='Problem solving'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='professional',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Attendance of Professional Meetings'), ('2', 'Provision of Professional education/talks')], default=1, max_length=3, verbose_name='Professional Contribution'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-14102020100', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-14102020169', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-14102020148', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-14102020104', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='adaptability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Relaibility'), ('2', 'Response to Change'), ('3', 'Ease of taking on other roles'), ('4', 'Attitude towards learning')], default=1, max_length=7, verbose_name='Adaptability & Flexibility'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Time keeping'), ('2', 'Commitment to duty')], default=1, max_length=3, verbose_name='Availability'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-14102020123', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledge',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Technical/Professional skills required'), ('2', 'Application'), ('3', 'Support and training to others')], default=1, max_length=5, verbose_name='Job Knowledge'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Relationship with Co-workers'), ('2', 'Clients or Team spirit and general work attitude')], default=1, max_length=3, verbose_name='Interpersonal Skills'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervision',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Work/task scheduling'), ('2', 'Meeting own/company targets'), ('3', 'Self-Supervision')], default=1, max_length=5, verbose_name='Supervision & Management'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='work',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Meeting Company Objectives'), ('2', 'Task Completeness'), ('3', 'Accuracy')], default=1, max_length=5, verbose_name='Work Quality & Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-14102020242', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-14102020101', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-14102020246', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
