# Generated by Django 3.0.2 on 2020-10-14 08:47

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0051_auto_20201014_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='availabilit',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Time keeping'), ('2', 'Commitment to duty')], default=1, max_length=3, verbose_name='Availability'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='interskills',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Relationship with Co-workers'), ('2', 'Clients or Team spirit and general work attitude')], default=1, max_length=3, verbose_name='Interpersonal Skills'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='supervisionmagt',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Work/task scheduling'), ('2', 'Meeting own/company targets'), ('3', 'Self-Supervision')], default=1, max_length=5, verbose_name='Supervision & Management'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='workquality',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Meeting Company Objectives'), ('2', 'Task Completeness'), ('3', 'Accuracy')], default=1, max_length=5, verbose_name='Work Quality & Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-14102020124', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-14102020157', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-14102020163', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-14102020288', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilit', to='operations_9001.providerparameters', verbose_name='10.\tAvailability Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-14102020145', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='operations_9001.providerparameters', verbose_name='7.\tInterpersonal Skills Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisio', to='operations_9001.providerparameters', verbose_name='9. Supervision & Management Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolv', to='operations_9001.providerparameters', verbose_name='6.\tWork Quality & Quantity Score:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-14102020110', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-14102020110', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-14102020263', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
