# Generated by Django 3.0.2 on 2020-10-14 13:23

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0055_auto_20201014_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='cost',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Financial'), ('2', 'Operational'), ('3', 'Legal/Regulatory'), ('4', 'Brand/Reputation')], default=100, max_length=7, verbose_name='Incident Cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='costdescription',
            field=models.IntegerField(default=100, verbose_name='Incident Cost Amount:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='currency',
            field=models.CharField(blank=True, choices=[('1', 'UGX'), ('2', 'USD'), ('3', 'Kshs'), ('4', 'GBP')], max_length=50, null=True, verbose_name='Currency:'),
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='lesson',
            field=models.TextField(blank=True, null=True, verbose_name='Lesson learnt:'),
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='status',
            field=models.TextField(blank=True, null=True, verbose_name='Compliant Status:'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-14102020117', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-14102020233', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-14102020200', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-14102020272', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='Initiativenes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Idea Development'), ('2', 'Effective use of resources'), ('3', 'Self drive/motivation')], max_length=5, null=True, verbose_name='4. Initiativeness & Resourcefulness'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availabilit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Time keeping'), ('2', 'Commitment to duty')], max_length=3, null=True, verbose_name='10. Availability'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Oral and Written'), ('2', 'Clarity of Information shared'), ('3', 'Accuracy of Information shared')], max_length=5, null=True, verbose_name='8. Communication Skills'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-14102020141', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='flexibility',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Relaibility'), ('2', 'Response to Change'), ('3', 'Ease of taking on other roles'), ('4', 'Attitude towards learning')], max_length=7, null=True, verbose_name='2. Adaptability & Flexibility'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='interskills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Relationship with Co-workers'), ('2', 'Clients or Team spirit and general work attitude')], max_length=3, null=True, verbose_name='7. Interpersonal Skills'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledg',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Technical/Professional skills required'), ('2', 'Application'), ('3', 'Support and training to others')], max_length=5, null=True, verbose_name='1. Job Knowledge'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='planing',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Establishing Priorities'), ('2', 'Meeting Deadlines'), ('3', 'Planning of Tasks')], max_length=5, null=True, verbose_name='5. Planning & Organisation'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='problemsolving',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Response promptness'), ('2', 'Level of Judgement'), ('3', 'Solution Quality')], max_length=5, null=True, verbose_name='3. Problem solving'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='professional',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Attendance of Professional Meetings'), ('2', 'Provision of Professional education/talks')], max_length=3, null=True, verbose_name='11. Professional Contribution'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervisionmagt',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Work/task scheduling'), ('2', 'Meeting own/company targets'), ('3', 'Self-Supervision')], max_length=5, null=True, verbose_name='9. Supervision & Management'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='workquality',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Meeting Company Objectives'), ('2', 'Task Completeness'), ('3', 'Accuracy')], max_length=5, null=True, verbose_name='6. Work Quality & Quantity'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-14102020169', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-14102020212', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-14102020109', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
