# Generated by Django 3.0.2 on 2020-10-28 08:38

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20201028_1138'),
        ('issues_9001', '0068_auto_20201028_1138'),
        ('operations_9001', '0067_auto_20201016_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod9001_providerassessment',
            name='nonconformity',
        ),
        migrations.RemoveField(
            model_name='mod9001_providerassessment',
            name='purpose',
        ),
        migrations.AddField(
            model_name='mod9001_incidentregisterstaff',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AddField(
            model_name='mod9001_incidentregisterstaff',
            name='scheduled',
            field=models.DateField(blank=True, null=True, verbose_name='Rescheduled Date:'),
        ),
        migrations.AddField(
            model_name='mod9001_incidentregisterstaff',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.RISK_OPPverification', verbose_name='Verification:'),
        ),
        migrations.AddField(
            model_name='mod9001_incidentregisterstaff',
            name='verification_failed',
            field=models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:'),
        ),
        migrations.AddField(
            model_name='mod9001_incidentregisterstaff',
            name='verification_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-28102020180', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-28102020292', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='clause',
            field=models.TextField(blank=True, null=True, verbose_name='Standard Clause:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-28102020229', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employees', verbose_name='Assigned to:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-28102020255', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='Communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communicatin', to='operations_9001.providerparameters', verbose_name='8. Communication Skills:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='adaptability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptabilit', to='operations_9001.providerparameters', verbose_name='2.\tAdaptability & Flexibility:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='assesment_date',
            field=models.DateField(null=True, verbose_name='Last Assessment Date:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilit', to='operations_9001.providerparameters', verbose_name='10.\tAvailability:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='cost',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Financial'), ('2', 'Operational'), ('3', 'Legal/Regulatory'), ('4', 'Brand/Reputation')], max_length=7, null=True, verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='costdescription',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cost Amount:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-28102020195', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='initiativeness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative', to='operations_9001.providerparameters', verbose_name='4.\tInitiativeness & Resourcefulness:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobknowledg', to='operations_9001.providerparameters', verbose_name='1. Job Knowledge:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannin', to='operations_9001.providerparameters', verbose_name='5. Planning & Organisation:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='problemsolve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolve', to='operations_9001.providerparameters', verbose_name='3.\tProblem Solving:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='professionalism',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professionalis', to='operations_9001.providerparameters', verbose_name='11. Professional Contribution:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='skills',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='operations_9001.providerparameters', verbose_name='7.\tInterpersonal Skills:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisio', to='operations_9001.providerparameters', verbose_name='9. Supervision & Management:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolv', to='operations_9001.providerparameters', verbose_name='6.\tWork Quality & Quantity:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-28102020177', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-28102020115', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='timeline',
            field=models.DateField(blank=True, null=True, verbose_name='Timeline:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-28102020161', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
