# Generated by Django 3.0.2 on 2020-11-04 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_auto_20201104_1013'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues_9001', '0080_auto_20201104_1013'),
        ('operations_9001', '0079_auto_20201030_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='CAR Source:')),
            ],
        ),
        migrations.CreateModel(
            name='containment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Containment Action:')),
            ],
        ),
        migrations.CreateModel(
            name='decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Decision or Action plan:')),
            ],
        ),
        migrations.CreateModel(
            name='element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Element:')),
            ],
        ),
        migrations.CreateModel(
            name='mod9001_correctiveaction',
            fields=[
                ('car_no', models.CharField(default='Comp-CAR-Q-04112020268', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:')),
                ('date', models.DateTimeField(null=True, verbose_name='CAR Date:')),
                ('reference', models.TextField(blank=True, null=True, verbose_name='Reference')),
                ('finding', models.CharField(choices=[('1', 'Non Conformity'), ('2', 'Observation')], max_length=200, verbose_name='Finding')),
                ('addesc', models.TextField(blank=True, null=True, verbose_name='Additional Description')),
                ('car_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.car_source', verbose_name='carsource:')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.element', verbose_name='element:')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.process', verbose_name='procestable:')),
                ('requesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.employees', verbose_name='Request to:')),
            ],
        ),
        migrations.CreateModel(
            name='root_cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Root Cause Analysis:')),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-04112020179', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-04112020133', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-04112020263', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-04112020239', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-04112020289', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-04112020292', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-04112020158', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-04112020110', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
        migrations.CreateModel(
            name='mod9001_planning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rootcause_desc', models.TextField(blank=True, null=True, verbose_name='Root Cause Description')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Additional Details')),
                ('due', models.DateTimeField(null=True, verbose_name='Due Date:')),
                ('rejected', models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Date Approved:')),
                ('verification_status', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_failed', models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approved_by', to=settings.AUTH_USER_MODEL)),
                ('assignedto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asigned_to', to='accounts.employees', verbose_name='Assigned to:')),
                ('car_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.mod9001_correctiveaction', verbose_name='carid:')),
                ('containment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.containment', verbose_name='containment:')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.decision', verbose_name='decision:')),
                ('proposedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proposed_to', to='accounts.employees', verbose_name='Proposed by:')),
                ('rootcause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.root_cause', verbose_name='rootcause:')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.RISK_OPPverification', verbose_name='Verification:')),
            ],
        ),
    ]
