# Generated by Django 3.0.2 on 2020-11-06 07:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0087_auto_20201106_1043'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues_9001', '0087_auto_20201106_1043'),
        ('operations_9001', '0086_auto_20201106_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Change type:')),
            ],
        ),
        migrations.CreateModel(
            name='evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Evaluation:')),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-06112020256', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-06112020201', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-06112020199', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-06112020278', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-06112020209', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-06112020215', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-06112020234', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-06112020126', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-06112020271', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
        migrations.CreateModel(
            name='mod9001_changeRegister',
            fields=[
                ('req_no', models.CharField(default='Comp-RFC-Q-06112020247', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:')),
                ('date', models.DateTimeField(null=True, verbose_name='Date:')),
                ('changedesc', models.TextField(blank=True, null=True, verbose_name='Change Description')),
                ('evaldesc', models.TextField(blank=True, null=True, verbose_name='Additional Description')),
                ('cost', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Financial'), ('2', 'Operational'), ('3', 'Legal/Regulatory'), ('4', 'Brand/Reputation'), ('5', 'Product/Service'), ('6', 'Customer Satisfaction')], max_length=11, null=True, verbose_name='Cost')),
                ('currency', models.CharField(blank=True, choices=[('1', 'UGX'), ('2', 'USD'), ('3', 'Kshs'), ('4', 'GBP')], max_length=50, null=True, verbose_name='Currency:')),
                ('add_desc', models.TextField(blank=True, null=True, verbose_name='Additional Description')),
                ('costdescription', models.IntegerField(blank=True, null=True, verbose_name='Cost Amount:')),
                ('rejected', models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='Date Approved:')),
                ('date_today', models.DateField(default=datetime.datetime.now, verbose_name='Date created:')),
                ('verification_status', models.CharField(blank=True, max_length=200, null=True)),
                ('verification_failed', models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:')),
                ('completion', models.DateField(blank=True, null=True, verbose_name='Completion Date:')),
                ('scheduled', models.DateField(blank=True, null=True, verbose_name='Rescheduled Date:')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approved_by2', to=settings.AUTH_USER_MODEL)),
                ('changetype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.change_type', verbose_name='Change Type:')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enter_by', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.evaluation', verbose_name='evaluation:')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.process', verbose_name='Process:')),
                ('qmsstatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:')),
                ('raisedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raised_by', to='accounts.employees', verbose_name='Raised by:')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.mod9001_correctiveaction', verbose_name='CAR Source:')),
                ('verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Carsverification', verbose_name='Verification:')),
            ],
        ),
    ]
