# Generated by Django 3.0.2 on 2021-05-07 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0118_auto_20210507_1106'),
        ('operations_9001', '0117_auto_20210426_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='completion',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='scheduled',
            field=models.DateField(blank=True, null=True, verbose_name='Rescheduled Date:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.RISK_OPPverification', verbose_name='Verification:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='verification_failed',
            field=models.TextField(blank=True, help_text='If rejected, please give a reason', null=True, verbose_name='Reason for rejecting:'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='verification_status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='TEGA-M-07052021224', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='TEGA-C-07052021254', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-07052021199', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-07052021113', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-07052021282', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-07052021100', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='TEGA-Q-07052021118', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-07052021280', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-07052021101', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='Comp-QP-07052021180', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-07052021241', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-07052021141', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
