# Generated by Django 3.2.3 on 2021-07-05 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0142_auto_20210705_1410'),
        ('accounts', '0142_auto_20210705_1410'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations_9001', '0141_auto_20210705_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='BCL-M-05072021210', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='BCL-C-05072021166', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cal_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approved_by2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='changetype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.change_type', verbose_name='Change Type:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enter_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.process', verbose_name='Process:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-05072021166', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='trigger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.car_source', verbose_name='Source:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.carsverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-05072021266', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.car_source', verbose_name='CAR source:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.element', verbose_name='Element:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correctiveactionentered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.process', verbose_name='Process:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.classification', verbose_name='Complaint Classification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-05072021263', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.correction', verbose_name='Correction/Containment:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='org', to='accounts.customer', verbose_name='Customer Organisation:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.process', verbose_name='Process:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.complaint_type', verbose_name='Complaint Type:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customeregistration',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Customer Organisation:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-05072021246', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='BCL-Q-05072021199', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregister',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='register_entered_byy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregister',
            name='incident_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.incident_description', verbose_name='Incident description:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregister',
            name='incidentype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.incident_type', verbose_name='incidentype:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregister',
            name='processname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.process', verbose_name='If Process, name:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.classification', verbose_name='Incident Classification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.correction', verbose_name='Correction/Containment:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidentstaff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='escalated',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalated', to=settings.AUTH_USER_MODEL, verbose_name='Responsible:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='rootcause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.rootcause', verbose_name='Root Cause:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_incidentregisterstaff',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Approved_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='car_no',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.mod9001_correctiveaction', verbose_name='CarNo:'),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='containment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.containment', verbose_name='containment:'),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.decision', verbose_name='decision:'),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planningentered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='rootcause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.root_cause', verbose_name='rootcause:'),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_planning',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.carsverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.process', verbose_name='procestable:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-05072021174', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-05072021208', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='providerentered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='operations_9001.mod9001_supplieregistration', verbose_name='External Provider Organisation:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='planner_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.mod9001_qmsplanner', verbose_name='QMS planner number:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qmsApprov_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qms_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='BCL-QP-05072021143', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_supplieregistration',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainplannerApprov_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_desc', to='operations_9001.train_desc'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planner_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='train_objective', to='operations_9001.train_objective'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-05072021132', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='trainplannerstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignedto', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-05072021156', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
    ]
