# Generated by Django 3.2.3 on 2021-07-27 09:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0180_auto_20210725_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod9001_providerassessment',
            name='interskills',
        ),
        migrations.RemoveField(
            model_name='mod9001_providerassessment',
            name='professional',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='BCL-M-27072021183', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='BCL-C-27072021141', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-27072021225', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-27072021213', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-27072021172', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-27072021220', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='BCL-Q-27072021263', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-27072021257', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='Initiativenes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Idea Development'), ('2', 'Effective use of resources')], max_length=3, null=True, verbose_name='4. Initiativeness & Resourcefulness'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availabilit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Time keeping'), ('2', 'Commitment')], max_length=3, null=True, verbose_name='10. Availability'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Oral and Written'), ('2', 'Clarity of Information shared'), ('3', 'Accuracy of Information shared')], max_length=5, null=True, verbose_name='8. Communication'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-27072021145', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='flexibility',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Relaibility'), ('2', 'Response to Change')], max_length=3, null=True, verbose_name='2. Adaptability & Flexibility'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledg',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Technical/Professional skills required'), ('2', 'Application'), ('3', 'Support and training')], max_length=5, null=True, verbose_name='1. Job Knowledge'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervisionmagt',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Work/task scheduling'), ('2', 'Self-Supervision')], max_length=3, null=True, verbose_name='9. Supervision & Management'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='BCL-QP-27072021286', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-27072021104', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-27072021262', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
