# Generated by Django 3.2.3 on 2021-07-30 18:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0182_auto_20210727_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='BCL-M-30072021261', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='BCL-C-30072021186', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-30072021263', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-30072021178', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-30072021165', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='due',
            field=models.DateField(null=True, verbose_name='When:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-30072021236', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='BCL-Q-30072021217', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-30072021119', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availabilit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Time keeping'), ('2', 'Commitment')], max_length=3, null=True, verbose_name='9. Availability'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='communication',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Oral and Written'), ('2', 'Clarity of Information shared'), ('3', 'Accuracy of Information shared')], max_length=5, null=True, verbose_name='7. Communication'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-30072021105', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledg',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Technical/Professional skills required'), ('2', 'Application'), ('3', 'Support and training')], max_length=5, null=True, verbose_name='1. Knowledge/Expertise'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervisionmagt',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Work/task scheduling'), ('2', 'Self-Supervision')], max_length=3, null=True, verbose_name='8. Supervision & Management'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='BCL-QP-30072021253', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-30072021158', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-30072021238', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
