# Generated by Django 3.2.3 on 2021-08-06 10:04

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0187_auto_20210805_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod9001_providerassessment',
            name='professionalism',
        ),
        migrations.RemoveField(
            model_name='mod9001_providerassessment',
            name='skills',
        ),
        migrations.AddField(
            model_name='mod9001_changeregister',
            name='costdesc',
            field=models.TextField(blank=True, null=True, verbose_name='Risks/Business Impacts Details'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='BCL-M-06082021196', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='BCL-C-06082021146', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-06082021214', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-06082021283', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-06082021176', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-06082021208', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='BCL-Q-06082021169', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-06082021151', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='Communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communicatin', to='operations_9001.providerparameters', verbose_name='7. Communication Skills:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='availability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilit', to='operations_9001.providerparameters', verbose_name='9.\tAvailability:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-06082021103', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledg',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', 'Technical/Professional skills required'), ('2', 'Application'), ('3', 'Support and training')], max_length=5, null=True, verbose_name='1.Knowledge/Expertise'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobknowledg', to='operations_9001.providerparameters', verbose_name='1. Knowledge/Expertise:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='rank',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Final Ranking: (Scores 1 to 9 are required)'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisio', to='operations_9001.providerparameters', verbose_name='8. Supervision & Management:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolv', to='operations_9001.providerparameters', verbose_name='6.Work Quality & Quantity:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='BCL-QP-06082021191', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-06082021190', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-06082021179', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
