# Generated by Django 3.2.3 on 2021-08-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0189_auto_20210806_1417'),
        ('issues_9001', '0189_auto_20210806_1417'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations_9001', '0188_auto_20210806_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='change_type_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Change type details:')),
            ],
        ),
        migrations.CreateModel(
            name='reason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reason:')),
            ],
        ),
        migrations.AddField(
            model_name='mod9001_changeregister',
            name='reason_details',
            field=models.TextField(blank=True, null=True, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='BCL-M-06082021135', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='BCL-C-06082021225', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Approved_by2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='assignedto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asigned', to='accounts.employees', verbose_name='Assigned to:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='changedesc',
            field=models.TextField(blank=True, null=True, verbose_name='Change Description details'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enter_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='proposedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed', to='accounts.employees', verbose_name='Proposed by:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-06082021181', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.carsverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-06082021188', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='assignedto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employees', verbose_name='Assigned to:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.classification', verbose_name='Complaint Classification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-06082021144', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='correction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.correction', verbose_name='Correction/Containment:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org', to='accounts.customer', verbose_name='Customer Organisation:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.process', verbose_name='Process:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.complaint_type', verbose_name='Complaint Type:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='assignedto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employees', verbose_name='Assigned to:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comm', to='operations_9001.providerparameters', verbose_name='4. Response to support:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='compliant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handlin', to='operations_9001.providerparameters', verbose_name='5. Service Reporting:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivtime', to='operations_9001.providerparameters', verbose_name='3. Complaint Handling/ Resolution:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='infosecurity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='securit', to='operations_9001.providerparameters', verbose_name='7. Overall quality of our products/ services:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Customer Organisation:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serv', to='operations_9001.providerparameters', verbose_name='6. Professionalism:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='resolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resotime', to='operations_9001.providerparameters', verbose_name='2. Knowledge of the products:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='responsetime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resptime', to='operations_9001.providerparameters', verbose_name='1. Time Management:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-06082021110', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='verification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.risk_oppverification', verbose_name='Verification:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='BCL-Q-06082021271', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-06082021193', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-06082021255', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='BCL-QP-06082021154', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-06082021177', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-06082021228', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
        migrations.AddField(
            model_name='mod9001_changeregister',
            name='changetype_desc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.change_type_desc', verbose_name='Change Type Desc:'),
        ),
        migrations.AddField(
            model_name='mod9001_changeregister',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.reason', verbose_name='Reason:'),
        ),
    ]
