# Generated by Django 3.2.3 on 2021-08-09 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0191_auto_20210806_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod9001_providerassessment',
            name='availability',
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='BCL-M-09082021133', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='BCL-C-09082021202', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-09082021109', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-09082021130', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-09082021172', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-09082021151', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='BCL-Q-09082021200', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-09082021151', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='Communication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communicatin', to='operations_9001.providerparameters', verbose_name='7.Complaints:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='adaptability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adaptabilit', to='operations_9001.providerparameters', verbose_name='2.Resolution Time:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-09082021151', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='initiativeness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative', to='operations_9001.providerparameters', verbose_name='4.Technical/Product Expertise:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='jobknowledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobknowledg', to='operations_9001.providerparameters', verbose_name='1.Response Time:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='planning',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plannin', to='operations_9001.providerparameters', verbose_name='5.Returns/Rejects:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='problemsolve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolve', to='operations_9001.providerparameters', verbose_name='3.Quality:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='rank',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Final Ranking: (Scores 1 to 8 are required)'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='supervision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisio', to='operations_9001.providerparameters', verbose_name='8.Pricing:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problemsolv', to='operations_9001.providerparameters', verbose_name='6.Delivery Rating:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='BCL-QP-09082021124', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-09082021137', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-09082021217', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
