# Generated by Django 3.2.3 on 2021-08-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations_9001', '0199_auto_20210813_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_calibration',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_changeregister',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_correctiveaction',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_customercomplaint',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_customersatisfaction',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_document_manager',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_incidentregister',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_incidentregisterstaff',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_planning',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_providerassessment',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_trainingregister',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_number',
            field=models.CharField(default='BCL-M-13082021240', max_length=200, primary_key=True, serialize=False, verbose_name='Maintenance no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_calibration',
            name='calibration_number',
            field=models.CharField(default='BCL-C-13082021136', max_length=200, primary_key=True, serialize=False, verbose_name='Calibration no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_changeregister',
            name='req_no',
            field=models.CharField(default='Comp-RFC-Q-13082021178', max_length=200, primary_key=True, serialize=False, verbose_name='Request No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_correctiveaction',
            name='car_no',
            field=models.CharField(default='Comp-CAR-Q-13082021287', max_length=200, primary_key=True, serialize=False, verbose_name='CAR No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customercomplaint',
            name='comp_no',
            field=models.CharField(default='Comp-COMP-Q-13082021256', max_length=200, primary_key=True, serialize=False, verbose_name='Complaint No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_customersatisfaction',
            name='satis_no',
            field=models.CharField(default='Comp-CS-Q-13082021206', max_length=200, primary_key=True, serialize=False, verbose_name='Satisfaction Survey No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_document_manager',
            name='document_number',
            field=models.CharField(default='BCL-Q-13082021208', max_length=200, primary_key=True, serialize=False, verbose_name='Document no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_processtable',
            name='process_number',
            field=models.CharField(default='Comp-Pr-13082021239', max_length=200, primary_key=True, serialize=False, verbose_name='Process ID:'),
        ),
        migrations.AlterField(
            model_name='mod9001_providerassessment',
            name='emp_perfrev_no',
            field=models.CharField(default='Comp-EA-Q-13082021205', max_length=200, primary_key=True, serialize=False, verbose_name='Performance Review No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_qmsplanner',
            name='planner_number',
            field=models.CharField(default='BCL-QP-13082021256', max_length=200, primary_key=True, serialize=False, verbose_name='Planner no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingplanner',
            name='plan_number',
            field=models.CharField(default='Comp-TP-13082021250', max_length=200, primary_key=True, serialize=False, verbose_name='Plan no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_trainingregister',
            name='training_number',
            field=models.CharField(default='Comp-TR-13082021156', max_length=200, primary_key=True, serialize=False, verbose_name='Training no.:'),
        ),
    ]
