# Generated by Django 3.0.2 on 2020-10-02 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0042_auto_20200921_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.CharField(default='TEGA-IP-Q-02102020211', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:')),
                ('name', models.TextField(verbose_name='DeptName:')),
                ('faculty', models.TextField(verbose_name='Faculty:')),
            ],
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-0210202071', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='quality_needs',
            field=models.CharField(choices=[('1', 'Communication'), ('2', 'Reporting'), ('3', 'Tax complaince'), ('4', 'CSR'), ('5', 'Time payment for services/products'), ('6', 'Timely delivery'), ('7', 'Safe work enviroment'), ('8', 'Operation support'), ('9', 'Work equipment'), ('10', 'Training'), ('11', 'Clear vision'), ('12', 'Quality support'), ('13', 'Performance feedback'), ('14', 'Contractual complaince'), ('15', 'legal complaince'), ('16', 'Business growth'), ('17', 'Performance')], max_length=200, verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-02102020639', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-02102020609', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-02102020859', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.CharField(default='TEGA-IP-Q-02102020376', max_length=200, primary_key=True, serialize=False, verbose_name='ID.:')),
                ('name', models.TextField(verbose_name='Name:')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues_9001.department', verbose_name='dept:')),
            ],
        ),
    ]
