# Generated by Django 3.0.2 on 2021-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0102_auto_20210325_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='TEGA-IP-Q-25032021809', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-25032021310', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-25032021290', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='process_desc',
            field=models.CharField(blank=True, choices=[('1', 'Transport'), ('2', 'Sales'), ('3', 'Administration'), ('4', 'Marketing'), ('5', 'Customer Relations'), ('6', 'Service/Help Desk Support'), ('7', 'Inventory'), ('8', 'Project Management'), ('9', 'Procurement'), ('10', 'Other'), ('11', 'Management'), ('12', 'Training'), ('13', 'Recruitment'), ('14', 'Systems Administration'), ('15', 'Disciplinary Process')], max_length=200, null=True, verbose_name='Process Description'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-25032021455', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-25032021891', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='TEGA-IP-Q-25032021496', max_length=200, primary_key=True, serialize=False, verbose_name='ID.:'),
        ),
    ]
