# Generated by Django 3.0.2 on 2021-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0116_auto_20210414_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='TEGA-IP-Q-26042021771', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='external_issues',
            field=models.CharField(blank=True, choices=[('1', 'Customers'), ('2', 'Regulators'), ('3', 'Hardware/Equipment Suppliers'), ('4', 'Traning providers'), ('5', 'Security providers'), ('6', 'Internet providers'), ('7', 'Insurance providers'), ('8', 'Auditors'), ('9', 'Certification bodies'), ('10', 'Inspectors'), ('11', 'Business partners'), ('12', 'Competitors'), ('13', 'Neighbourhood'), ('14', 'Local authorities'), ('15', 'Family'), ('16', 'Suppliers'), ('17', 'Prescribers'), ('18', 'NGOs'), ('19', 'Influencers'), ('19', 'Customers Customers'), ('20', 'Customers'), ('21', 'Regulators')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-26042021714', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-26042021928', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='process_desc',
            field=models.CharField(blank=True, choices=[('1', 'Transport'), ('2', 'Sales'), ('3', 'Administration'), ('4', 'Marketing'), ('5', 'Customer Relations'), ('6', 'Service/Help Desk Support'), ('7', 'Inventory'), ('8', 'Project Management'), ('9', 'Procurement'), ('10', 'Other'), ('11', 'Management'), ('12', 'Training'), ('13', 'Recruitment'), ('14', 'Systems Administration'), ('15', 'Disciplinary Process'), ('16', 'Accounts Payables'), ('17', 'Accounts Receivables')], max_length=200, null=True, verbose_name='Process Description'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-26042021268', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-26042021733', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='TEGA-IP-Q-26042021456', max_length=200, primary_key=True, serialize=False, verbose_name='ID.:'),
        ),
    ]
