# Generated by Django 3.0.2 on 2021-05-13 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0121_auto_20210512_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='interestedparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='TEGA-IP-Q-13052021510', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='TEGA-IP-Q-13052021104', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='TEGA-CT-Q-13052021776', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='interestedparty',
            field=models.CharField(blank=True, choices=[('1', 'Customers'), ('2', 'Regulators'), ('3', 'Hardware/Equipment Suppliers'), ('4', 'Training providers'), ('5', 'Security providers'), ('6', 'Internet providers'), ('7', 'Insurance providers'), ('8', 'Auditors'), ('9', 'Certification bodies'), ('10', 'Inspectors'), ('11', 'Business partners'), ('12', 'Competitors'), ('13', 'Neighbourhood'), ('14', 'Local authorities'), ('15', 'Family'), ('16', 'Other')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='TEGA-IP-LRO-Q-1305202128', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='TEGA-RA-13052021456', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='TEGA-IP-Q-13052021740', max_length=200, primary_key=True, serialize=False, verbose_name='ID.:'),
        ),
        migrations.AddField(
            model_name='mod9001_issues',
            name='interestedparties',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='issues_9001.interestedparty', verbose_name='interestedparty'),
        ),
    ]
