# Generated by Django 3.2.3 on 2021-08-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0185_auto_20210804_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_issues',
            name='analyst_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Analyst Sytem UserID.:'),
        ),
        migrations.AddField(
            model_name='mod9001_regulatoryreq',
            name='analyst_user_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Analyst Sytem UserID.:'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='BCL-IP-Q-04082021209', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='BCL-IP-Q-04082021515', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='BCL-CT-Q-0408202187', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='BCL-IP-LRO-Q-04082021792', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='BCL-RA-04082021460', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='BCL-IP-Q-04082021463', max_length=200, primary_key=True, serialize=False, verbose_name='ID.:'),
        ),
    ]
