# Generated by Django 3.2.3 on 2021-08-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_9001', '0199_auto_20210813_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod9001_interestedparties',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_issues',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_regulatoryreq',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AddField(
            model_name='mod9001_risks',
            name='record_group',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data Group'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='BCL-IP-Q-13082021544', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_interestedparties',
            name='ip_number',
            field=models.CharField(default='BCL-IP-Q-13082021649', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_issues',
            name='issue_number',
            field=models.CharField(default='BCL-CT-Q-13082021852', max_length=200, primary_key=True, serialize=False, verbose_name='Issue no.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_regulatoryreq',
            name='regulatory_number',
            field=models.CharField(default='BCL-IP-LRO-Q-13082021908', max_length=200, primary_key=True, serialize=False, verbose_name='IP No.:'),
        ),
        migrations.AlterField(
            model_name='mod9001_risks',
            name='risk_number',
            field=models.CharField(default='BCL-RA-13082021968', max_length=200, primary_key=True, serialize=False, verbose_name='RISK No.:'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.CharField(default='BCL-IP-Q-13082021572', max_length=200, primary_key=True, serialize=False, verbose_name='ID.:'),
        ),
    ]
