# Generated by Django 3.0.2 on 2020-12-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0096_auto_20201230_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='TEGA31122020878', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='TEGA263', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
