# Generated by Django 3.0.2 on 2021-03-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0105_auto_20210329_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_titles',
            fields=[
                ('title_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Title ID:')),
                ('title_name', models.TextField(verbose_name='Name:')),
            ],
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='TEGA2903202163', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='TEGA579', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
        migrations.AddField(
            model_name='employees',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportsTo', to='accounts.Employee_titles', verbose_name='Supervisor:'),
        ),
        migrations.AddField(
            model_name='employees',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='accounts.Employee_titles', verbose_name='Title:'),
        ),
    ]
