# Generated by Django 3.0.2 on 2021-04-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_auto_20210414_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='TEGA26042021706', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='TEGA234', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
