# Generated by Django 3.0.2 on 2021-05-13 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_auto_20210513_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='TEGA1305202161', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='TEGA387', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
