# Generated by Django 3.2.3 on 2021-07-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0142_auto_20210705_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Company address:'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_person',
            field=models.CharField(max_length=200, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='customer',
            name='job_title',
            field=models.CharField(max_length=200, null=True, verbose_name='Contact Person Title'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='BCL05072021419', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='BCL236', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
