# Generated by Django 3.2.3 on 2021-07-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0145_auto_20210706_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='BCL07072021232', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='BCL230', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
