# Generated by Django 3.2.3 on 2021-07-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0147_auto_20210707_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='BCL0807202131', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='BCL998', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
