# Generated by Django 3.2.3 on 2021-07-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0149_auto_20210708_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='BCL09072021691', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='BCL188', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
