# Generated by Django 3.2.3 on 2021-08-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0186_auto_20210804_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_number',
            field=models.CharField(default='BCL05082021669', max_length=200, primary_key=True, serialize=False, verbose_name='Corrective action no.:'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employeeID',
            field=models.CharField(default='BCL334', max_length=10, primary_key=True, serialize=False, verbose_name='Employee ID'),
        ),
    ]
