# Generated by Django 3.2.3 on 2021-07-17 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('itsms_20000', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mod20000_service_planning',
            old_name='Solution',
            new_name='solution',
        ),
        migrations.RemoveField(
            model_name='mod20000_service_planning',
            name='completion',
        ),
        migrations.AddField(
            model_name='mod20000_service_planning',
            name='planning_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date:'),
            preserve_default=False,
        ),
    ]
