# Generated by Django 3.2.3 on 2021-07-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsms_20000', '0002_auto_20210717_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod20000_service_planning',
            name='verification',
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='verification_status',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
