# Generated by Django 3.2.3 on 2021-07-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsms_20000', '0003_auto_20210717_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod20000_service_request',
            name='requestor',
            field=models.TextField(blank=True, null=True, verbose_name='Requestor'),
        ),
    ]
