# Generated by Django 3.2.3 on 2021-08-10 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations_9001', '0193_auto_20210810_2219'),
        ('issues_9001', '0193_auto_20210810_2219'),
        ('accounts', '0193_auto_20210810_2219'),
        ('itsms_20000', '0005_alter_mod20000_service_request_entered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='AssignedTo:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='completedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employees', verbose_name='Completed by:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='component_affected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itsms_20000.component', verbose_name='Component Affected:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='entered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations_9001.qmsstatus', verbose_name='Verification Status:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itsms_20000.service_category', verbose_name='Service Category:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='service_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='itsms_20000.scope', verbose_name='Service scope:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='issues_9001.approval_status', verbose_name='Status:'),
        ),
    ]
