# Generated by Django 3.2.3 on 2021-08-14 18:16

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsms_20000', '0007_auto_20210813_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod20000_service_planning',
            name='document',
            field=models.FileField(null=True, upload_to='documents/', validators=[accounts.utils.validate_file_size], verbose_name='Upload Support Document:'),
        ),
        migrations.AddField(
            model_name='mod20000_service_planning',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
