# Generated by Django 3.2.3 on 2021-08-14 19:27

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsms_20000', '0008_auto_20210814_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='document',
            field=models.FileField(default=123, upload_to='documents/', validators=[accounts.utils.validate_file_size], verbose_name='Upload Support Document:'),
            preserve_default=False,
        ),
    ]
