# Generated by Django 3.2.3 on 2021-08-17 09:59

import accounts.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsms_20000', '0011_auto_20210815_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[accounts.utils.validate_file_size_verification], verbose_name='Upload Support Document:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_planning',
            name='planning_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Date:'),
        ),
        migrations.AlterField(
            model_name='mod20000_service_request',
            name='date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Request Date:'),
        ),
    ]
